# Generated by Django 5.1.5 on 2025-02-01 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_bookinfo_commentcount_bookinfo_is_delete_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinfo',
            options={'verbose_name': '书籍信息'},
        ),
        migrations.AlterModelTable(
            name='bookinfo',
            table='book_info',
        ),
    ]
